### ISSUE TITLE
matlu ilotalo events

### ISSUE THREAD

**Issue by JaniL** [TKOaly/info-screen#44]
Perhaps add TKO-äly events from Klusteri calendar to the screen?

Some events might not end up in the TKO-äly event calendar, such as UEFA Champions League / The Premier League watch parties.

Requires either:

1) Deploying this https://github.com/JaniL/bmur-reservation-api and consuming it
2) Code HTML scraper functionality to this repo

**Comment by MergHQ** [comment]
Here's an API that you can use instead of using a scraper: https://ilotalo.matlu.fi/api/events/

**Comment by ConcernedHobbit** [comment]
> Here's an API that you can use instead of using a scraper: https://ilotalo.matlu.fi/api/events/

is there some way to limit the resulting json file? e.g. a `afterDate` parameter or similar so we could limit the resulting data to events today and in the future.

**Comment by MergHQ** [comment]
No way to do that, it's a shitty PHP viritelmä

**Comment by Jokauppi** [comment]
Will implement this again in the redesign, can get its own slide to not clutter up the already full TKO-äly one
